# Data source configurations for threat intelligence frameworks
data_sources:
  mitre_attack:
    url: "https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json"
    format: "stix"
    description: "MITRE ATT&CK Enterprise framework data"
    entity_types:
      - tactics
      - techniques
      - groups
      - mitigations