# Entity type schemas for different security frameworks
entity_schemas:
  tactic:
    id_field: "id"
    name_field: "name"
    description_field: "description"
    required_fields: ["id", "name", "description"]
    
  technique:
    id_field: "id"
    name_field: "name"
    description_field: "description"
    required_fields: ["id", "name", "description"]
    optional_fields: ["tactics", "platforms", "mitigations"]
    
  group:
    id_field: "id"
    name_field: "name"
    description_field: "description"
    required_fields: ["id", "name", "description"]
    optional_fields: ["aliases", "techniques"]
    
  mitigation:
    id_field: "id"
    name_field: "name"
    description_field: "description"
    required_fields: ["id", "name", "description"]
    optional_fields: ["techniques"]