name: Claude Code Review

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@claude') || github.event_name == 'pull_request_review_comment'
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
    - name: Claude Code Review
      uses: anthropics/claude-code-action@v0.0.54
      with:
        anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
        github-token: ${{ secrets.GITHUB_TOKEN }}